name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push admin_frontend Docker image
        working-directory: admin_frontend
        run: |
          docker build -t l00179208/sgproject/admin_frontend:$GITHUB_SHA -f Dockerfiles/Dockerfile .
          docker push l00179208/sgproject/admin_frontend:$GITHUB_SHA

      - name: Build and push studio_ghibli Docker image
        working-directory: frontend/studio_ghibli
        run: |
          docker build -t l00179208/sgproject/studio_ghibli:$GITHUB_SHA -f Dockerfiles/Dockerfile .
          docker push l00179208/sgproject/studio_ghibli:$GITHUB_SHA

      - name: Build and push backend services Docker images
        run: |
          docker build -t l00179208/sgproject/courses:$GITHUB_SHA -f backend/courses/Dockerfiles/Dockerfile ./backend/courses
          docker push l00179208/sgproject/courses:$GITHUB_SHA

          docker build -t l00179208/sgproject/customers:$GITHUB_SHA -f backend/customers/Dockerfiles/Dockerfile ./backend/customers
          docker push l00179208/sgproject/customers:$GITHUB_SHA

          # Repeat for other backend services...

      - name: SSH deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker-compose -f DockerCompose/docker-compose.yml pull
            docker-compose -f DockerCompose/docker-compose.yml up -d
