name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Fetches the entire repository code

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $DOCKER_USERNAME/sgproject:admin_frontend ./admin_frontend Dockerfiles/Dockerfile .
          docker build -t $DOCKER_USERNAME/sgproject:studio_ghibli_frontend ./frontend/studio-ghibli Dockerfiles/Dockerfile .
          docker build -t $DOCKER_USERNAME/sgproject:gateway ./backend/gateway Dockerfiles/Dockerfile .
          docker build -t $DOCKER_USERNAME/sgproject:courses ./backend/courses Dockerfiles/Dockerfile .
          docker build -t $DOCKER_USERNAME/sgproject:enrollment ./backend/enrollment Dockerfiles/Dockerfile .
          docker build -t $DOCKER_USERNAME/sgproject:customers ./backend/customers Dockerfiles/Dockerfile .
          docker build -t $DOCKER_USERNAME/sgproject:users ./backend/users Dockerfiles/Dockerfile .

          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

          docker tag $DOCKER_USERNAME/sgproject:admin_frontend $DOCKER_USERNAME/sgproject:admin_frontend-$IMAGE_TAG
          docker tag $DOCKER_USERNAME/sgproject:studio_ghibli_frontend $DOCKER_USERNAME/sgproject:studio_ghibli_frontend-$IMAGE_TAG
          docker tag $DOCKER_USERNAME/sgproject:gateway $DOCKER_USERNAME/sgproject:gateway-$IMAGE_TAG
          docker tag $DOCKER_USERNAME/sgproject:courses $DOCKER_USERNAME/sgproject:courses-$IMAGE_TAG
          docker tag $DOCKER_USERNAME/sgproject:enrollment $DOCKER_USERNAME/sgproject:enrollment-$IMAGE_TAG
          docker tag $DOCKER_USERNAME/sgproject:customers $DOCKER_USERNAME/sgproject:customers-$IMAGE_TAG
          docker tag $DOCKER_USERNAME/sgproject:users $DOCKER_USERNAME/sgproject:users-$IMAGE_TAG

          docker push $DOCKER_USERNAME/sgproject:admin_frontend-$IMAGE_TAG
          docker push $DOCKER_USERNAME/sgproject:studio_ghibli_frontend-$IMAGE_TAG
          docker push $DOCKER_USERNAME/sgproject:gateway-$IMAGE_TAG
          docker push $DOCKER_USERNAME/sgproject:courses-$IMAGE_TAG
          docker push $DOCKER_USERNAME/sgproject:enrollment-$IMAGE_TAG
          docker push $DOCKER_USERNAME/sgproject:customers-$IMAGE_TAG
          docker push $DOCKER_USERNAME/sgproject:users-$IMAGE_TAG

      - name: SSH Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          debug: true
          script: |
            ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "IMAGE_TAG=${{ github.sha }} bash -s" < deploy.sh
