name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print environment variables
        run: env

      - name: Print directory structure for debugging
        run: |
          echo "Checking directory structure"
          ls -R
          ls -R ../admin_frontend
          ls -R ../backend/courses
          ls -R ../backend/gateway
          ls -R ../backend/customers
          ls -R ../backend/users
          ls -R ../backend/enrollment
          ls -R ../backend/sql

      - name: Check Docker version
        run: docker --version

      - name: Check Docker Compose version
        run: docker-compose --version

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push images
        run: |
          echo "Building and pushing Docker images"
          docker-compose -f path/to/your/docker-compose.yml build
          docker-compose -f path/to/your/docker-compose.yml push

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy .env file
        run: |
          scp -i ${{ secrets.AWS_SSH_KEY }} .env ubuntu@${{ secrets.EC2_IP }}:/home/ubuntu

      - name: SSH and deploy
        run: |
          ssh -i ${{ secrets.AWS_SSH_KEY }} ubuntu@${{ secrets.EC2_IP }} << 'EOF'
            cd /home/ubuntu/sgproject
            docker-compose pull
            docker-compose up -d
          EOF