name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print environment variables
        run: env

      - name: Print directory structure for debugging
        run: |
          echo "Checking directory structure"
          ls -R
          ls -R DockerCompose

      - name: Check Docker version
        run: docker --version

      - name: Check Docker Compose version
        run: docker-compose --version

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push images
        run: |
          cd DockerCompose
          echo "Running docker-compose build"
          docker-compose build --verbose
          echo "Pushing Docker images to l00179208/sgproject"
          docker-compose push l00179208/sgproject


  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy .env file
        run: |
          scp -i ${{ secrets.AWS_SSH_KEY }} .env ubuntu@${{ secrets.EC2_IP }}:/home/ubuntu

      - name: SSH and deploy
        run: |
          ssh -i ${{ secrets.AWS_SSH_KEY }} ubuntu@${{ secrets.EC2_IP }} << 'EOF'
            cd /home/ubuntu/sgproject
            docker-compose pull
            docker-compose up -d
          EOF
