name: Deploy Application to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.0

      - name: Terraform Init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Apply
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform apply -auto-approve
        working-directory: ./terraform

      - name: Build admin frontend
        working-directory: ./admin_frontend
        run: |
          npm install
          npm run build

      - name: Build course backend
        working-directory: ./backend/course
        run: |
          npm install
          npm run build

      - name: Build customers backend
        working-directory: ./backend/customers
        run: |
          npm install
          npm run build

      - name: Build enrollment backend
        working-directory: ./backend/enrollment
        run: |
          npm install
          npm run build

      - name: Build gateway backend
        working-directory: ./backend/gateway
        run: |
          npm install
          npm run build

      - name: Build studio-ghibli frontend
        working-directory: ./frontend/studio-ghibli
        run: |
          npm install
          npm run build

      - name: Deploy Docker Compose
        env:
          INSTANCE_IP: ${{ secrets.INSTANCE_IP }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass
          sshpass -p ${{ secrets.SSH_PASSWORD }} ssh -o StrictHostKeyChecking=no -i $SSH_PRIVATE_KEY ubuntu@$INSTANCE_IP << EOF
            cd /home/ubuntu/your_project_directory
            git pull origin master
            sudo docker-compose -f docker-compose.yml up -d --build
          EOF
