name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push admin_frontend Docker image
        working-directory: admin_frontend
        run: |
          docker build -t l00179208/sgproject:admin_frontend -f Dockerfiles/Dockerfile .
          docker tag l00179208/sgproject:admin_frontend l00179208/sgproject:admin_frontend-$GITHUB_SHA
          docker push l00179208/sgproject:admin_frontend:$GITHUB_SHA

      - name: SSH deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }} 
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker-compose -f DockerCompose/docker-compose.yml pull
            docker-compose -f DockerCompose/docker-compose.yml up -d
