name: Terraform Security Scan

on:
  push:
    branches: [ master ]  # Change to your desired branch(es)

jobs:
  terrascan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set AWS Credentials (optional)
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: echo "AWS credentials set for Terraform (optional)"      

      - name: Install Terrascan
        uses: tenable/terrascan-action@v1
        with:
          terrascan_version: 'latest'  # Or specify a specific version

      - name: Run Terrascan Scan
        run: terrascan scan ./iac

      - name: Upload SARIF results (optional)
        uses: reviewdog/reviewdog@v2
        with:
          name: Terrascan
          reporter: github-check
          level: warning  # Change to desired severity level
          fail_ci: true  # Fail build if vulnerabilities are found
          input_format: terrascan  # Specify Terrascan output format
          github_token: ${{ secrets.GITHUB_TOKEN }}
